spring.application.name=moviemate-backend

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/moviemate
spring.datasource.username=${DB_POSTGRE_USERNAME}
spring.datasource.password=${DB_POSTGRE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Evita que Spring intente usar un datasource embebido
# spring.sql.init.mode=never

# Server
server.port=8080

#JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000 # 24 horas en ms

# Logging
logging.level.com.moviemate=DEBUG
logging.level.org.springframework.security=DEBUG