apiVersion: v1
kind: Service
metadata:
  name: {{ include "moviemate.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "moviemate.labels" . | nindent 4 }}
    {{- include "moviemate.postgres.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "moviemate.postgres.selectorLabels" . | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
